image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB : mahjoub_hamdi8
  APP_NAME : ProductManager
  REPO : Stage_4A

stages:
  - build
  - docker
maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      -  target/ProductManager.jar

docker-build:
  stage: docker
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/mahjoubhamdi8/$REPO .
  - docker push registry.gitlab.com/mahjoubhamdi8/$REPO 
